spring:
  datasource:
    url: jdbc:h2:mem:test
    username: admin
  jpa:
    show-sql: true
    defer-datasource-initialization: true

#  tworzy baze danych H2 ktora sie tworzy oraz wykorzystuje do uzupełnienia data.sql