spring:
  profiles:
#    wybór profilu
    active: dev
  liquibase:
#    okreslenie pliku głównego
    change-log: classpath:db/master.xml
#    okreslenie jaki profil moze korzystac z liquibase
    contexts: dev, prod
